# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish package to pub.dev

on:
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.3'
          channel: 'stable'

      - name: Run tests
        run: flutter test --machine test

  publish:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Setup Credentials
        uses: joutvhu/write-file@v1
        with:
          path: ~/.pub-cache/credentials.json
          contents: ${{ secrets.PUB_CREDENTIALS }}
          write_mode: overwrite

      - name: Publish package
        run: pub publish -f
